# Generated by Django 2.1.3 on 2018-11-11 13:07

import Profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=Profiles.models.upload_location)),
                ('colour', models.CharField(default='D3D3D3', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api_team_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='teamLogos')),
                ('colour', models.CharField(default='D3D3D3', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawable_bank', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('non_withdrawable_bank', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=Profiles.models.upload_location)),
                ('colour', models.CharField(blank=True, max_length=7, null=True)),
                ('ranking', models.IntegerField(default=0)),
                ('founder', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('status', models.CharField(choices=[('sent', 'Active'), ('declined', 'Deactivated'), ('declined_blocked', 'Declined and Blocked'), ('active', 'Active'), ('deactivated', 'Deactivated'), ('requesting_invite', 'Requesting invite')], default='active', max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups_wallet', to='Groups.CommunityGroup')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inviters_wallet', to='Profiles.Profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles_wallet', to='Profiles.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(related_name='groups_profile', through='Profiles.Wallet', to='Groups.CommunityGroup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('profile', 'group')},
        ),
    ]
