# Generated by Django 2.1.3 on 2019-05-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='picture',
        ),
        migrations.AddField(
            model_name='team',
            name='picture_id',
            field=models.IntegerField(default=1),
        ),
    ]
