# Generated by Django 2.1.3 on 2019-05-06 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Games', '0001_initial'),
        ('Groups', '0001_initial'),
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Lost', 'Lost'), ('Paid', 'Paid')], default='Open', max_length=30)),
                ('winnings', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('chosen_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Profiles.Team')),
                ('chosen_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Profiles.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='MatchBettingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_mbgs', to='Groups.CommunityGroup')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_mbgs', to='Games.Match')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='match_betting_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mbg_bets', to='Bets.MatchBettingGroup'),
        ),
        migrations.AddField(
            model_name='bet',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_bets', to='Profiles.Wallet'),
        ),
        migrations.AlterUniqueTogether(
            name='matchbettinggroup',
            unique_together={('match', 'group')},
        ),
    ]
