# Generated by Django 2.1.3 on 2018-11-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('private', models.BooleanField(default=False)),
                ('daily_payout', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('removable', models.BooleanField(default=True)),
                ('max_users', models.IntegerField(default=32)),
                ('total_users', models.IntegerField(default=0, editable=False)),
                ('members_can_inv', models.BooleanField(default=True)),
                ('header_background_colour', models.CharField(default='ffffff', max_length=7)),
                ('header_text_colour', models.CharField(default='000000', max_length=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=30)),
            ],
        ),
    ]
