# Generated by Django 2.1.3 on 2019-05-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='picture',
        ),
        migrations.AddField(
            model_name='videogame',
            name='picture_id',
            field=models.IntegerField(default=1),
        ),
    ]
