# Generated by Django 2.1.3 on 2018-11-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='series',
            name='owning_group',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='series',
        ),
        migrations.AddField(
            model_name='tournament',
            name='groups',
            field=models.ManyToManyField(related_name='group_series', to='Groups.CommunityGroup'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='owning_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='owning_group_series', to='Groups.CommunityGroup'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='twitch_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
