# Generated by Django 2.1.3 on 2018-11-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_auto_20181117_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='groups',
            field=models.ManyToManyField(related_name='group_tournaments', to='Groups.CommunityGroup'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='owning_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='owning_group_tournaments', to='Groups.CommunityGroup'),
        ),
    ]
