# Generated by Django 2.1.3 on 2018-12-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0003_auto_20181117_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='twitch_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='twitch_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
